version: '{build} - {branch}'
image: Visual Studio 2017
platform: x64

skip_non_tags: true

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

environment:
  nodejs_version: '10'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm ci

test: off

build_script:
  - npm run build
  - ps: npm version $env:APPVEYOR_REPO_TAG_NAME.Substring(1) --no-git-tag-version
  - npm run builder
