language: node_js
node_js: '9'

stages:
  - name: release
    if: branch = master AND type != pull_request
  - name: publish
    if: tag IS present
  # - name: test
  #   if: tag IS blank

notifications:
  email: false

cache: yarn

jobs:
  include:
    - stage: release
      script: yarn semantic-release
    - stage: publish
      os: linux
      addons:
        apt:
          packages:
            - icnsutils
            - graphicsmagick
      before_script:
        - yarn build
        - yarn version --new-version "${TRAVIS_TAG:1:${#TRAVIS_TAG}}" --no-git-tag-version
      script: yarn builder
    - stage: publish
      os: osx
      osx_image: xcode9.0
      before_script:
        - yarn build
        - yarn version --new-version "${TRAVIS_TAG:1:${#TRAVIS_TAG}}" --no-git-tag-version
      script: yarn builder
