language: node_js
node_js: '10'

stages:
  - name: release
    if: branch = master AND type != pull_request
  - name: publish
    if: tag IS present

notifications:
  email: false

jobs:
  include:
    - stage: release
      script: npx semantic-release
    - stage: publish
      os: linux
      addons:
        apt:
          packages:
            - icnsutils
            - graphicsmagick
      before_script:
        - npm ci
        - npm run build
        - npm version "${TRAVIS_TAG:1:${#TRAVIS_TAG}}" --no-git-tag-version
      script: npm run builder
    - stage: publish
      os: osx
      osx_image: xcode9
      before_script:
        - npm ci
        - npm run build
        - npm version "${TRAVIS_TAG:1:${#TRAVIS_TAG}}" --no-git-tag-version
      script: npm run builder
